/**
 *  THE CONTENT OF THIS FILE IS AUTOGENERATED BY THE CLI. DONT EDIT IT DIRECTLY
 *  If you need to edit the template, to to libs/cli/src/commands/feature.ts
 */
import { mergeQueryKeys, type inferQueryKeyStore } from '@lukemorales/query-key-factory';
import { authKeys } from '../auth/utils/auth.keys';
import { todoKeys } from '../todo/utils/todo.keys';

export const queryKeys = mergeQueryKeys(authKeys, todoKeys);
export type QueryKeys = inferQueryKeyStore<typeof queryKeys>;
