/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignupForm: typeof import('./src/features/user/components/SignupForm.vue')['default']
    TodoForm: typeof import('./src/features/todo/components/TodoForm.vue')['default']
    TodoList: typeof import('./src/features/todo/components/TodoList.vue')['default']
  }
}
