/**
 *  THE CONTENT OF THIS FILE IS AUTOGENERATED BY THE CLI. DONT EDIT IT DIRECTLY
 *  If you need to edit the template, to to libs/cli/src/commands/feature.ts
 */
import { initContract } from '@ts-rest/core';
import { arenaContract } from './features/arena';
import { authContract } from './features/auth';
import { heroContract } from './features/hero';
import { userContract } from './features/user';

const c = initContract();

export const contract = c.router(
  {
    arena: arenaContract,
    auth: authContract,
    hero: heroContract,
    user: userContract
  },
  {
    strictStatusCodes: true,
    pathPrefix: '/api'
  }
);

export type Contract = typeof contract;
