/**
 *  THE CONTENT OF THIS FILE IS AUTOGENERATED BY THE CLI. DONT EDIT IT DIRECTLY
 *  If you need to edit the template, to to libs/cli/src/commands/feature.ts
 */
import { initContract } from '@ts-rest/core';
import { authContract } from './features/auth';
import { todoContract } from './features/todo';
import { userContract } from './features/user';

const c = initContract();

export const contract = c.router(
  {
    auth: authContract,
    todo: todoContract,
    user: userContract
  },
  {
    strictStatusCodes: true,
    pathPrefix: '/api'
  }
);

export type Contract = typeof contract;
